import streamlit as st
import pandas as pd

from predict import predict_fraud


st.set_page_config(
    page_title="Credit Card Fraud Detection",
    page_icon="💳",
    layout="centered"
)


st.title("💳 Credit Card Fraud Detection")

st.write(
    "Enter transaction details to predict whether a transaction "
    "is potentially fraudulent."
)
st.caption(
    "Portfolio demonstration only — predictions are generated by a "
    "machine learning model and should not be treated as a final "
    "financial or fraud decision."
)
st.subheader("Transaction Details")

st.caption(
    "Enter the transaction's elapsed time and purchase amount. "
    "Time is measured in seconds from the first transaction in the dataset."
)

col1, col2 = st.columns(2)

with col1:
    time_value = st.number_input(
        "Time",
        min_value=0.0,
        value=0.0
    )

with col2:
    amount = st.number_input(
        "Amount",
        min_value=0.0,
        value=0.0
    )

with st.expander("🔐 Anonymized Transaction Features"):

    st.caption(
    "V1–V28 are anonymized PCA-transformed features from the original dataset. "
    "They do not have directly interpretable business meanings."
)

    col1, col2, col3 = st.columns(3)

    with col1:
        v1 = st.number_input("V1", value=0.0)
        v2 = st.number_input("V2", value=0.0)
        v3 = st.number_input("V3", value=0.0)
        v4 = st.number_input("V4", value=0.0)
        v5 = st.number_input("V5", value=0.0)
        v6 = st.number_input("V6", value=0.0)
        v7 = st.number_input("V7", value=0.0)
        v8 = st.number_input("V8", value=0.0)
        v9 = st.number_input("V9", value=0.0)

    with col2:
        v10 = st.number_input("V10", value=0.0)
        v11 = st.number_input("V11", value=0.0)
        v12 = st.number_input("V12", value=0.0)
        v13 = st.number_input("V13", value=0.0)
        v14 = st.number_input("V14", value=0.0)
        v15 = st.number_input("V15", value=0.0)
        v16 = st.number_input("V16", value=0.0)
        v17 = st.number_input("V17", value=0.0)
        v18 = st.number_input("V18", value=0.0)

    with col3:
        v19 = st.number_input("V19", value=0.0)
        v20 = st.number_input("V20", value=0.0)
        v21 = st.number_input("V21", value=0.0)
        v22 = st.number_input("V22", value=0.0)
        v23 = st.number_input("V23", value=0.0)
        v24 = st.number_input("V24", value=0.0)
        v25 = st.number_input("V25", value=0.0)
        v26 = st.number_input("V26", value=0.0)
        v27 = st.number_input("V27", value=0.0)
        v28 = st.number_input("V28", value=0.0)



transaction = pd.DataFrame([{
    "Time": time_value,
    "V1": v1,
    "V2": v2,
    "V3": v3,
    "V4": v4,
    "V5": v5,
    "V6": v6,
    "V7": v7,
    "V8": v8,
    "V9": v9,
    "V10": v10,
    "V11": v11,
    "V12": v12,
    "V13": v13,
    "V14": v14,
    "V15": v15,
    "V16": v16,
    "V17": v17,
    "V18": v18,
    "V19": v19,
    "V20": v20,
    "V21": v21,
    "V22": v22,
    "V23": v23,
    "V24": v24,
    "V25": v25,
    "V26": v26,
    "V27": v27,
    "V28": v28,
    "Amount": amount
}])

st.caption(
    "Decision threshold: 39%. Transactions with a fraud probability "
    "of 39% or higher are flagged for review."
)
if st.button("🔍 Predict Fraud"):
    probability, prediction = predict_fraud(transaction)

    st.metric(
        "Fraud Probability",
        f"{probability:.2%}"
    )

    st.progress(probability)

    if prediction == 1:
        st.error("🚨 FRAUD DETECTED")
        st.warning(
            "This transaction should be flagged for further review."
        )
    else:
        st.success("✅ TRANSACTION APPEARS LEGITIMATE")
        st.info(
            "The model does not identify this transaction as fraudulent "
            "at the current decision threshold."
        )

st.divider()

st.subheader("🤖 Model Information")

st.write("**Model:** Random Forest Classifier")
st.write("**Decision threshold:** 39%")
st.write("**Validation-selected threshold:** Yes")
st.write("**Primary evaluation focus:** Precision, Recall, F1-score and PR-AUC")

st.divider()

st.subheader("📖 How to Interpret the Result")

st.write(
    "The model outputs a fraud probability between 0% and 100%. "
    "If the probability is at or above 39%, the transaction is flagged "
    "for further review. Otherwise, it is classified as legitimate."
)